{"name": "Невозможно создать пользователя, который уже зарегистрирован", "status": "passed", "description": "При попытке создать пользователя, который уже зарегистрирован, получаем ответ с кодом 403 и в body есть сообщение \"User already exists\"", "steps": [{"name": "Зарегистрировать нового пользователя", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'xoddyauymp@yandex.ru', 'password': 'aklljmkxpc', 'name': 'vtjxhkhesi'}"}], "start": 1715662967617, "stop": 1715662967756}], "start": 1715662967617, "stop": 1715662967757, "uuid": "8fd23bf4-a337-4ed2-a788-5f32aa73c775", "historyId": "e30a3b19b366582438e333180de341de", "testCaseId": "e30a3b19b366582438e333180de341de", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_already_registered_forbidden", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "MacBook-Air--Dmitry.local"}, {"name": "thread", "value": "62712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}